[package]
name = "aoc_2020_rs"
version = "0.1.0"
authors = ["Nick Timkovich <prometheus235@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
